{% set name = "napari-generic-simulator" %}
{% set version = "0.0.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-generic-SIMulator-{{ version }}.tar.gz
  sha256: cefa2890ea01658abb86d7b8c02ba9038d1a347c4a5e3cf0b12e52dcf7c6067f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - magicgui
    - napari
    - numpy
    - opt-einsum
    - python >=3.8
    - qtpy
    - tifffile

test:
  imports:
    - napari_generic_simulator
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Meizhu-Liang/napari-generic-SIMulator
  summary: A simple plugin to use with napari to simulate raw image stacks in Structured illumination microscopy (SIM) with napari.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
